#!/usr/bin/env bash
# This script transfers a file from our client to a server

path=$(pwd)
filename=$(basename "$BASH_SOURCE")

if [ $# -eq 4 ]
then
	scp -i $4 $path/$1 $3@$2:/home/$3/
else
	echo -e "Usage: $filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
