#!/usr/bin/env bash
# Fixes the issue with the server

pkill -f apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx -s /bin/bash -c 'service nginx start'
